version: '3'

services:
  bike-summary-producer:
    container_name: bike-summary-producer
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: bike_summary
      SLEEP_TIME: 60

networks:
  default:
    external:
      name: kafka-network